### ISSUE TITLE
'/' at the end of the path to watch breaks moving files

### ISSUE THREAD

**Issue by dietervanhoof** [viaacode/ftp-watchfolder#4]
/home/export/vrt/incoming/dailies/essence/
!=
/home/export/vrt/incoming/dailies/essence

Moving adds a '/' which makes a file path look like the following:
/home/export/vrt/incoming/dailies/essence//file.mxf

MAKE SURE YOU DON'T HAVE A / AT THE END OF THE PATH

**Comment by maartends** [comment]
Should be fixed. Closing.
